### ISSUE TITLE
cannot launch the biab box for some...

### ISSUE THREAD

**Issue by fungreenfox** [andrepl/BuildInABox#30]
a user reported that he cannot spawn a little hoverpad (made of 8xwood and 8wool proxymately). It has normally no problems in spawning, and when i went to his GP claim, he had it trusted to another guy also, should be no problem. i asked him to make another claim and try spawning it there. He could not spawn it there. I spawned it for him in that new claim, and he was able to use this pad asap. (similar to magic carped).
I have not other reports of this, excecpt a user who could not spawn the blacksmith, where i could. I think i have given out all permissions. Have you changed anything about  permissions?

Here are the permission given to the group the normal user is in:
    - biab.lock.*
    - biab.pickup.*
    - biab.place.*
    - biab.unlock.*

**Comment by andrepl** [comment]
the build permissions check has had some changes, it's got specific checks for grief prevention claims and WG Regions now, so its possible that there's a bug in that code somewhere.  are you able to reproduce that situation if the user creates a new claim and tries again?  If so I will add some specific debugging to the next build so that we can track down the issue better.

**Comment by fungreenfox** [comment]
i can deal out the hoverpad to a few players to see.

**Comment by fungreenfox** [comment]
it works fine for another guy on his GP claim. I guess some ppl has a lesser good understanding for right and left or something. They are not very old, so its limited what i can answere to. Lets presume it works.

**Comment by andrepl** [comment]
ok, re-open this if you can manage to reproduce the issue.
